name: Create build Windows🧐🙈

on: 
  workflow_dispatch: {}
    

jobs:
  build:
    name: Build for Unity ✨
    runs-on: windows-2019
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: false

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      # - name: Apply Wwise Fix
      - run: |
          "C:\Program Files\Unity\Hub\Editor\${{ secrets.UNITY_VERSION }}\Editor\Unity.exe" -batchmode -quit -projectPath . -executeMethod WwiseFixEditor.ApplyWwiseScriptsFix
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}


      # Build
      - name: Build project
        uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
